package com.yerelrotam.app;

import android.app.*;import android.os.*;import android.content.*;import android.graphics.Color;import android.graphics.Typeface;import android.view.*;import android.widget.*;import java.text.*;import java.util.*;

public class MainActivity extends Activity {
    LinearLayout root, content; TextView title, points; SharedPreferences sp;
    int green=Color.rgb(15,107,67), light=Color.rgb(235,247,240), dark=Color.rgb(28,39,34), gray=Color.rgb(100,115,107);
    public void onCreate(Bundle b){super.onCreate(b);sp=getSharedPreferences("yerel",0);showHome();}
    TextView tv(String s,int size,boolean bold){TextView t=new TextView(this);t.setText(s);t.setTextSize(size);t.setTextColor(dark);t.setTypeface(Typeface.DEFAULT,bold?Typeface.BOLD:Typeface.NORMAL);t.setPadding(18,12,18,12);return t;}
    Button btn(String s){Button b=new Button(this);b.setText(s);b.setTextColor(Color.WHITE);b.setTextSize(15);b.setAllCaps(false);b.setBackgroundColor(green);return b;}
    void base(String screen){root=new LinearLayout(this);root.setOrientation(LinearLayout.VERTICAL);root.setBackgroundColor(Color.rgb(248,251,249));
      LinearLayout bar=new LinearLayout(this);bar.setGravity(Gravity.CENTER_VERTICAL);bar.setPadding(8,12,8,8);title=tv(screen,22,true);title.setTextColor(green);bar.addView(title,new LinearLayout.LayoutParams(0,60,1));
      TextView p=tv("🌿 "+sp.getInt("points",0)+"",17,true);p.setTextColor(green);bar.addView(p,new LinearLayout.LayoutParams(-2,60));root.addView(bar);
      ScrollView sc=new ScrollView(this);content=new LinearLayout(this);content.setOrientation(LinearLayout.VERTICAL);content.setPadding(16,6,16,20);sc.addView(content);root.addView(sc,new LinearLayout.LayoutParams(-1,0,1));
      LinearLayout nav=new LinearLayout(this);nav.setPadding(4,4,4,4);nav.setBackgroundColor(Color.WHITE);String[] ns={"Ana Sayfa","Yolculuk","Geçmiş","Liderlik","Profil"};for(String n:ns){Button x=new Button(this);x.setText(n);x.setTextSize(11);x.setAllCaps(false);x.setTextColor(gray);nav.addView(x,new LinearLayout.LayoutParams(0,58,1));x.setOnClickListener(v->{if(n.equals("Ana Sayfa"))showHome();else if(n.equals("Yolculuk"))showTrip();else if(n.equals("Geçmiş"))showHistory();else if(n.equals("Liderlik"))showBoard();else showProfile();});}root.addView(nav);setContentView(root);}
    TextView card(String s){TextView t=tv(s,15,false);t.setBackgroundColor(Color.WHITE);t.setPadding(18,18,18,18);LinearLayout.LayoutParams lp=new LinearLayout.LayoutParams(-1,-2);lp.setMargins(0,7,0,7);t.setLayoutParams(lp);return t;}
    void showHome(){base("Yerel Rotam");int p=sp.getInt("points",0), free=sp.getInt("free",0);content.addView(tv("Toplu taşımayla yolculuk yap, şehrine katkı sağ!",25,true));content.addView(card("🌱 Yeşil Puan\n"+p+" puan  •  "+(50-p%50)+" puan sonra bir sonraki ücretsiz biniş"));content.addView(card("🎟️ Ücretsiz Biniş Hakkı\n"+free+" adet kullanılabilir"));content.addView(card("💳 Kart\n"+(sp.getString("card","Kart eklenmedi"))));Button b=btn("🚍 Yolculuk ekle");content.addView(b);b.setOnClickListener(v->showTrip());content.addView(card("🏆 Bu ay liderlikte yüksel!\nİl içindeki toplam yeşil puanına göre sıralamanı takip et."));}
    void showTrip(){base("Yolculuk Ekle");content.addView(tv("Kaç kilometrelik toplu taşıma yolculuğu yaptın?",20,true));EditText e=new EditText(this);e.setHint("Mesafe (km)");e.setInputType(2|8192);content.addView(e);Spinner mode=new Spinner(this);String[] a={"Otobüs","Metro","Tren","Tramvay"};mode.setAdapter(new ArrayAdapter<String>(this,android.R.layout.simple_spinner_dropdown_item,a));content.addView(mode);Button b=btn("Yeşil Puanı Hesapla");content.addView(b);b.setOnClickListener(v->{try{double km=Double.parseDouble(e.getText().toString());int add=km<15?1:km<30?2:km<50?3:5;int old=sp.getInt("points",0), total=old+add, free=sp.getInt("free",0)+total/50;total%=50;sp.edit().putInt("points",total).putInt("free",free).putInt("rides",sp.getInt("rides",0)+1).putString("last",new SimpleDateFormat("dd.MM.yyyy HH:mm",Locale.TR).format(new Date())+" • "+mode.getSelectedItem()+" • "+km+" km • +"+add+" puan").apply();new AlertDialog.Builder(this).setTitle("Yolculuk kaydedildi 🌿").setMessage("+"+add+" Yeşil Puan kazandın!\nToplam puanın: "+total+(free>sp.getInt("free",0)-1?"\nÜcretsiz biniş hakkın oluştu!":"")).setPositiveButton("Tamam",(d,w)->showHome()).show();}catch(Exception z){e.setError("Mesafe girin");}});content.addView(card("Puanlama\n0–15 km → 1 puan\n15–30 km → 2 puan\n30–50 km → 3 puan\n50 km ve üzeri → 5 puan\n\n50 Yeşil Puan = 1 ücretsiz toplu taşıma binişi"));}
    void showHistory(){base("Geçmiş");int r=sp.getInt("rides",0);content.addView(card("Toplam yolculuk: "+r+"\nSon işlem: "+sp.getString("last","Henüz yolculuk eklenmedi")));content.addView(card("📊 Kazanım mantığı\nHer toplu taşıma yolculuğu mesafesine göre puanlanır. Bu prototipte yolculuklar kullanıcı tarafından girilmektedir."));}
    void showBoard(){base("İl Liderliği");content.addView(tv("Bu ay — Yeşil Puan sıralaması",20,true));String[] names={"Ece Y.","Mert K.","Zeynep A.","Deniz T.","Sen"};int[] ps={186,164,151,137,sp.getInt("points",0)+120};for(int i=0;i<names.length;i++){content.addView(card((i+1)+".  "+names[i]+" — "+ps[i]+" Yeşil Puan"));}content.addView(card("🎁 Ay sonu ödülleri\n1. → +100 puan\n2. → +75 puan\n3. → +50 puan"));}
    void showProfile(){base("Profil & Kart");content.addView(card("👤 Profil\nİsim: "+sp.getString("name","Demo Kullanıcı")+"\nİl: İzmir"));content.addView(card("💳 Toplu Taşıma Kartı\nKart: "+sp.getString("card","35-XXXX-XXXX-1234")+"\nBakiye: "+sp.getString("balance","125,50 TL")+"\n\nNot: Gerçek kart bakiyesi için belediye/ulaşım işletmesinin resmi API entegrasyonu gerekir."));EditText name=new EditText(this);name.setHint("Profil adını değiştir");content.addView(name);Button save=btn("Profili kaydet");content.addView(save);save.setOnClickListener(v->{if(name.getText().length()>0)sp.edit().putString("name",name.getText().toString()).apply();showProfile();});}
}
